### ISSUE TITLE
python3.8  ValueError: Array conditional must be same shape as self

### ISSUE THREAD

**Issue by hackeye** [practical-jupyter/sample-data#1]
![image](https://user-images.githubusercontent.com/25793057/111556456-9f8c2100-87c5-11eb-8a85-705c5215143e.png)

**Comment by drillan** [comment]
This code is working fine in my environment and in Colab.

https://colab.research.google.com/github/practical-jupyter/sample-code/blob/master/notebooks/3-06.ipynb

Can I see all of the codes?

As an additional check point. The shape of the DataFrame should be as follows.

```python
df.shape
```

```python
(10486, 7)
```

```python
(df["rating"] < 9.2).shape
```

```python
(10486,)
```

**Comment by hackeye** [comment]
This code is working fine in Colab,so I check the enviroment.
```
!pip list pandas
```
The version of pandas is 1.1.5 but mine is 1.2.3.

![image](https://user-images.githubusercontent.com/25793057/111717826-d3ce1300-8893-11eb-9627-cbf7f0ed6041.png)

mine

![image](https://user-images.githubusercontent.com/25793057/111717876-e8aaa680-8893-11eb-8e63-d12dc0b52ee8.png)

When I change the version of pandas, the code works fine.

![image](https://user-images.githubusercontent.com/25793057/111718275-9453f680-8894-11eb-89ae-36ea9801ed93.png)
